### ISSUE TITLE
The server works on HTTP-only!

### ISSUE THREAD

**Issue by GabubuAvailable** [agarian-2/MultiOgar#12]
Like the title says, I tried to make a public server for my friends and I find out that the client communicates with the server on HTTP-only. If I try to do the same thing but on HTTPS... it doesn't work... It stays at "Connecting" pop-up only... It is somehow possible to make the server communicate in HTTPS with the client? Nowadays browsers do automatically switch to HTTPS if you type "HTTP://example.org" in URL bar...

**Comment by agarian-2** [comment]
Unfortunately since https://agarian-2.github.io/ is https, it completely disallows any http connection to an agar.io server unless it's localhost. Nothing I can do about it, the best I can say is to download the client and then it'll work in http.
